
name: compiling kernel

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

env:
  KERNEL_SOURCE: https://github.com/AndroidBlobs/kernel_xiaomi_vayu
  BRANCH: release-LA.UM.9.1.r1-07000-SMxxx0.0
  DEFCONFIG: vayu_user_defconfig
  TZ: Asia/Kolkata
  MIR: wet
  TOOLCHAIN: https://github.com/mvaisakh/gcc-arm
  TOOLCHAIN2: https://github.com/mvaisakh/gcc-arm64
  ARCH: arm64
  SUBARCH: arm64
  FOLDERNAME: kernel-automation
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc libssl-dev  rsync flex bison ccache 
            mkdir ~/bin && PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
       - name: Cloning repo
         run: |
            git clone --recurse-submodules $KERNEL_SOURCE --depth=1 --branch=$BRANCH work
       - name: Compiling Kernel
         run: |
            cd work
            git clone $TOOLCHAIN --depth=1
            git clone $TOOLCHAIN2 --depth=1 
            CROSS_COMPILE="pwd/gcc-arm64/bin/aarch64-elf-"
            CROSS_COMPILE_ARM32="pwd/gcc-arm/bin/arm-linux-gnueabi"
            export CROSS_COMPILE
            export ARCH=$ARCH
            export SUBARCH=$SUBARCH
            mkdir out
            make O=out $DEFCONFIG
            make O=out -j8
       - name: Uploading process
         run: |
            cd work/arch/arm64/boot
            curl -sL https://git.io/file-transfer | sh
            ./transfer $MIR Image.gz-dtb
