
name: compiling kernel

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

env:
  KERNEL_SOURCE: https://github.com/leeminh888/kernel_xiaomi_vayu
  BRANCH: r
  DEFCONFIG: vayu_user_defconfig
  TZ: Asia/Kolkata
  MIR: wet
  TOOLCHAIN: https://github.com/mvaisakh/gcc-arm
  TOOLCHAIN2: https://github.com/mvaisakh/gcc-arm64
  ARCH: arm64
  SUBARCH: arm64
  FOLDERNAME: kernel-automation
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc libssl-dev  rsync flex bison ccache 
            chmod +x build.sh && ./buildx.sh
       - name: Uploading process
         run: |
            cd work/kernel_xiaomi_vayu/AnyKernel3
            curl -sL https://git.io/file-transfer | sh
            ./transfer *.zip
